// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mesosphere/kudo-kafka-operator/images/kafka-utils/pkgs/service (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	"github.com/golang/mock/gomock"

	"reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// WriteIngressToPath mocks base method
func (m *MockService) WriteIngressToPath(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteIngressToPath", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteIngressToPath indicates an expected call of WriteIngressToPath
func (mr *MockServiceMockRecorder) WriteIngressToPath(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteIngressToPath", reflect.TypeOf((*MockService)(nil).WriteIngressToPath), arg0)
}
