export DOCKER_IMAGE_VERSION="1.2.1"
export KAFKA_VERSION="2.4.1"
export CRUISE_CONTROL_VERSION="2.0.77"
export CRUISE_CONTROL_UI_VERSION="0.3.4"

export KAFKA_TAG_VERSION=${KAFKA_VERSION}-${DOCKER_IMAGE_VERSION}
export CRUISE_CONTROL_TAG_VERSION=${CRUISE_CONTROL_VERSION}-${DOCKER_IMAGE_VERSION}
