DOCKER_IMAGE_VERSION="1.1.0"
KAFKA_VERSION="2.4.0"
CRUISE_CONTROL_VERSION="2.0.77"
CRUISE_CONTROL_UI_VERSION="0.3.4"

KAFKA_TAG_VERSION=${KAFKA_VERSION}-${DOCKER_IMAGE_VERSION}
CRUISE_CONTROL_TAG_VERSION=${CRUISE_CONTROL_VERSION}-${DOCKER_IMAGE_VERSION}
